data <- read.table("./household_power_consumption.txt", sep=";" , header= TRUE , skip= 66636, nrows= 2880, na.strings="?", col.names= c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3"))
date4<- as.POSIXct(paste(data[,1], data[,2]), format="%d/%m/%Y %H:%M:%S")
par(mfcol= c(2,2), mar= c(4,4,1,1))
plot(date4,data[,3], type= "l", xlab="", ylab="Global Active Power (kilowatts)")
plot(date4,data[,7], type="n", xlab="", ylab="Energy Sub Metering")
lines(date4,data[,7], col="black")
lines(date4,data[,8], col="red")
lines(date4,data[,9], col="blue")
legend("topright", legend= c("Sub_Metering_1","Sub_Metering_2","Sub_Metering_3"), lty=1, col= c("black","red","blue"),cex=0.5)
plot(date4,data[,5], type="l", xlab="datetime", ylab="Voltage")
plot(date4,data[,4], type="l",xlab="datetime", ylab="Global Reactive Power")
dev.copy(png, file="myplot4.png")
dev.off()